
STATUS_NEW_GAME = '100'

STATUS_GAME_OVER = '200'
STATUS_GET_INIT_CARDS = '201'
STATUS_EXCHANGE_CARDS = '202'
STATUS_PLAY_CARD = '203'
STATUS_GET_CARD = '204'

STATUS_WAIT_FOR_INIT_CARDS = '401'
STATUS_WAIT_FOR_EXCHANGE_CARDS = '402'
STATUS_WAIT_FOR_GET_CARD = '403'

RESPONSE_GAME_OVER = '300'
RESPONSE_GAME_OVER_NO_CARD = '301'
RESPONSE_PLAY_CARD = '302'
RESPONSE_GET_SELF_CARD = '303'
RESPONSE_GET_OTHER_CARD = '304'
